### ISSUE TITLE
malformed packet when doing SASL authentication

### ISSUE THREAD

**Issue by yuvalif** [vchekan/wireshark-kafka#2]
using the latest code, kafka communication is dissected correctly except for the SASL authenticate stage:

request:
```
Kafka (SaslAuthenticate v0 Request)
    Length: 40
    API Key: SaslAuthenticate (36)
    API Version: 0
    Correlation ID: 3
    Client ID: rdkafka
    SASL Authentication Bytes: <MISSING>
    [Expert Info (Warning/Malformed): Dissected message does not end at the pdu length offset]
        [Dissected message does not end at the pdu length offset]
        [Severity level: Warning]
        [Group: Malformed]
```
```
0000   00 00 00 28 00 24 00 00 00 00 00 03 00 07 72 64   ...(.$........rd
0010   6b 61 66 6b 61 00 00 00 13 00 61 6c 69 63 65 00   kafka.....alice.
0020   61 6c 69 63 65 2d 73 65 63 72 65 74               alice-secret
```
response;
```
Kafka (SaslAuthenticate v0 Response)
    Length: 12
    Correlation ID: 3
    [Request Frame: 12]
    [API Key: SaslAuthenticate (36)]
    [API Version: 0]
    Error: No Error (0)
    Error Message: 
    SASL Authentication Bytes: <MISSING>
    [Expert Info (Warning/Malformed): Dissected message does not end at the pdu length offset]
        [Dissected message does not end at the pdu length offset]
        [Severity level: Warning]
        [Group: Malformed]
```
```
0000   00 00 00 0c 00 00 00 03 00 00 00 00 00 00 00 00   ................
```
note that the actual authentication between the client and the server went well.
and that the user ("alice") and password (alice-secret") appear in the ascii dump of the request are correct.

**Comment by vchekan** [comment]
Strange, I thought, that this is what `tcp_dissect_pdus` is for: https://github.com/vchekan/wireshark-kafka/blob/a559232ac8d1ab74ce885ee53358997cad39b28e/src/dissects.rs#L24-L33

I'll try to reproduce.

**Comment by vchekan** [comment]
Ah, I think I found it. From kafka protocol documentation: 
> If SaslHandshakeRequest version is v0, a series of SASL client and server tokens corresponding to the mechanism are sent as opaque packets without wrapping the messages with Kafka protocol headers.

**Comment by vchekan** [comment]
Reproduced.

**Comment by vchekan** [comment]
I think you are looking at the output of wiresharks-supplied kafka dissector, which is buggy and incomplete. Mine has name `Kafka4r`. You can open wireshark's "About" menu and make sure that plugin has been picked up. I've added better description to `readme.md` recently.

Notice dissector name is `Kafka4r`:
```
Kafka4r (SaslAuthenticate v1 Request)
    Length: 30
    API Key: SaslAuthenticate (36)
    API Version: 1
    Correlation Id: 2
    Client Id: 
        String Length: 0
        String: 
    Auth bytes: 0075736572310070617373776f726431

```

**Comment by vchekan** [comment]
Let me know is it is still a problem or you plugin does not register in wireshark for some reason.

**Comment by yuvalif** [comment]
to me the issue is stil lthere.
i followed the instructions in the readme, and its says the file name is `libkafka_plugin.so` not `Kafka4r`.
this is what i see in the about->plugins window:
```
libkafka_plugin.so		0.0.0		dissector		/home/ylifshit/.local/lib/wireshark/plugins/3.6/epan/libkafka_plugin.so
```

**Comment by vchekan** [comment]
Ok, this looks correct. 
When you start wireshark, do you run it under this user or do you do `sudo wireshark`? If you use `sudo`, then plugin would bee looked up by wireshark under `/root` folder.

Another test.
1. Right click on "Kafka" line in top window (where data stream is, not in the detail window)
2. "Decode As ..."
3. What is your "Default" column?
4. Can you change "Current" to kafka4r?

**Comment by yuvalif** [comment]
I don't use sudo, just run it from my user. when I try to "Decode As..." there is only "Kafka" in the list, no "Kafka4r"

**Comment by vchekan** [comment]
Strange, seems like plugin has been loaded, so dissector must be in there. Are you sure it is missing? List of dissectors is not sorted by the name but I think it is in adding order, so kafla4r would be the last item in the drop-down.

**Comment by yuvalif** [comment]
> Strange, seems like plugin has been loaded, so dissector must be in there. Are you sure it is missing? List of dissectors is not sorted by the name but I think it is in adding order, so kafla4r would be the last item in the drop-down.

yes it was at the end of the list. working now, thanks!
